[package]

name = "emit"
version = "0.0.1"
authors = ["Geoffry Song <goffrie@gmail.com>"]

[dependencies.ast]

path = "../ast"

[dependencies.middle]

path = "../middle"

[dependencies.rbtree]

path = "../rbtree"

[dependencies.getopts]

version = "0.2.9"
